spring:
    profiles:
        default: dev

    jpa:
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

shelters:
    tsunami_key: ${TSUNAMI_KEY}
    earthquake_key: ${EARTHQUAKE_KEY}

files:
    civil_defense: csv/civil_defense_shelter_20221020.csv
    area: csv/address_202201.csv